//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisplayAutoRotation.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DisplayAutoRotation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string About_String {
            get {
                return ResourceManager.GetString("About_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Внимание.
        /// </summary>
        internal static string Attention_String {
            get {
                return ResourceManager.GetString("Attention_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть приложение?.
        /// </summary>
        internal static string Close_App_String {
            get {
                return ResourceManager.GetString("Close_App_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Control Interface.
        /// </summary>
        internal static string Cont_Interface_Modem {
            get {
                return ResourceManager.GetString("Cont_Interface_Modem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корректировка нулевого положения дисплея.
        /// </summary>
        internal static string Corr_String {
            get {
                return ResourceManager.GetString("Corr_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Автоматический поворот экрана по данным акселерометра G-Sensor от Bosch. Добавлено управление встроенным GPS..
        /// </summary>
        internal static string Description_String {
            get {
                return ResourceManager.GetString("Description_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение параметров не удалось, потому что система DualView.
        /// </summary>
        internal static string DISP_CHANGE_BADDUALVIEW_String {
            get {
                return ResourceManager.GetString("DISP_CHANGE_BADDUALVIEW_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применён недопустимый набор флагов.
        /// </summary>
        internal static string DISP_CHANGE_BADFLAGS_String {
            get {
                return ResourceManager.GetString("DISP_CHANGE_BADFLAGS_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Этот графический режим не поддерживается.
        /// </summary>
        internal static string DISP_CHANGE_BADMODE_String {
            get {
                return ResourceManager.GetString("DISP_CHANGE_BADMODE_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применён недопустимый параметр. Это может относиться к указанию неверного флага или комбинации флагов.
        /// </summary>
        internal static string DISP_CHANGE_BADPARAM_String {
            get {
                return ResourceManager.GetString("DISP_CHANGE_BADPARAM_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Драйвер дисплея завершил ошибкой заданный графический режим..
        /// </summary>
        internal static string DISP_CHANGE_FAILED_String {
            get {
                return ResourceManager.GetString("DISP_CHANGE_FAILED_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно записать данные в реестр.
        /// </summary>
        internal static string DISP_CHANGE_NOTUPDATED_String {
            get {
                return ResourceManager.GetString("DISP_CHANGE_NOTUPDATED_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для применения параметров необходимо перегрузить систему.
        /// </summary>
        internal static string DISP_CHANGE_RESTART_String {
            get {
                return ResourceManager.GetString("DISP_CHANGE_RESTART_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть и очистить.
        /// </summary>
        internal static string GPS_Clear_String {
            get {
                return ResourceManager.GetString("GPS_Clear_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GPS Interface.
        /// </summary>
        internal static string GPS_Interface_Modem {
            get {
                return ResourceManager.GetString("GPS_Interface_Modem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слушать порт.
        /// </summary>
        internal static string GPS_Read_Stirng {
            get {
                return ResourceManager.GetString("GPS_Read_Stirng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включить GPS.
        /// </summary>
        internal static string GPS_Start_String {
            get {
                return ResourceManager.GetString("GPS_Start_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выключить GPS.
        /// </summary>
        internal static string GPS_Stop_String {
            get {
                return ResourceManager.GetString("GPS_Stop_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon hoplik {
            get {
                object obj = ResourceManager.GetObject("hoplik", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hor_0 {
            get {
                object obj = ResourceManager.GetObject("Hor_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hor_1 {
            get {
                object obj = ResourceManager.GetObject("Hor_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hor_2 {
            get {
                object obj = ResourceManager.GetObject("Hor_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hor_3 {
            get {
                object obj = ResourceManager.GetObject("Hor_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon Off {
            get {
                object obj = ResourceManager.GetObject("Off", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon On {
            get {
                object obj = ResourceManager.GetObject("On", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перегрузить систему сейчас?.
        /// </summary>
        internal static string Restart_Now_String {
            get {
                return ResourceManager.GetString("Restart_Now_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не определёно текущее положение экрана.
        /// </summary>
        internal static string Screen_orientation_unknown {
            get {
                return ResourceManager.GetString("Screen_orientation_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свернуть.
        /// </summary>
        internal static string Size_Min {
            get {
                return ResourceManager.GetString("Size_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Развернуть.
        /// </summary>
        internal static string Size_Normal {
            get {
                return ResourceManager.GetString("Size_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия.
        /// </summary>
        internal static string Version_String {
            get {
                return ResourceManager.GetString("Version_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Vert_0 {
            get {
                object obj = ResourceManager.GetObject("Vert_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сброс корректировки на 0.
        /// </summary>
        internal static string Zero_String {
            get {
                return ResourceManager.GetString("Zero_String", resourceCulture);
            }
        }
    }
}
